language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: '7.0'
  fast_finish: true

script:
    - phpunit -c app/
    - vendor/behat/behat/bin/behat
    -  vendor/phpspec/phpspec/bin/phpspec run

cache:
    composer: true
    directories: vendor